language: java

sudo: required

# skip installation step
install: true

services:
 - docker

install:
 - docker pull mongo

before_install:
 sh -e /etc/init.d/xvfb start;

addons:
  sonarcloud:
       branches:
		-master
		-continuous_integration
    organization: "georgesmiley-github"
    token:
      secure:  "LwG+i2HywWN9sBG8oH4zPdHaNfHflto4bN9urO/mucJr2z/96YeWBkmN6DHgd7VKssVcwfAyb1eUPPoBrnzcyPt7KH6K3Go/Jt5mfFDrp/u66ccNklU/DqB8ZiJdWHvxSVscWLUUDO6DFzi9VPG8th7SibFizm/+ESMem+znodWer/k9fHxtnbi0wks74YIscMDsZsh+Zr/Ikr58fexjFMIlmz1NE5rk2zbfnKfKejraFFgPnd9b8iEkcORIzlbxnm7ISuX9X43NJMML4urifuMMJ4qpu+pPbtX1k7kWiLB5sDoDlr9FyQMMoNvrPJsp2CpXrcwZOFK2auLZk0qqP0zOWXN8FHOSdpkq9McXFPsCvNhjRbHgoMAxf5vny00vqE0w9tD3BLcCqqxBTL4Czk/QAZ+ZSJvNXmcJOHrXqL8Byi5gZY47Zu9h0SFbybiLZUbVTKj6Gq5ML2W9VJnbMErGm8P7qOsrkkQzUyrYoEO95WrK9A1YzUu4ruLzoAOqWdpxfnfZZ8uWcncQs+b6ighymVPUwprDcZO/8bfAxDy9D2uvV4jr3ulLndJQVE/R4bUqH5PHZi6PxHeoo1ewmXx789INnsqDxw6yjhYg4IAWe3FofkmkvK5LSya08HVLONv4UITFMJXZ6vvkICg+bFm4E/jmqjvTVpr5hVCslTg="

script:
  - mvn -f plex-data-handler/pom.xml clean verify -Pjacoco coveralls:report
  - mvn -f plex-data-handler/pom.xml clean verify -Pfailsafe
cache:
  directories:
  - $HOME/.m2
